name: SkyServerBase
version: '${project.version}'
main: se.skynet.skyserverbase.SkyServerBase

depend:
  - ProtocolLib

commands:
  fly:
  build:
  ban:
  kick:
  configcreator:
  nick:
  unnick:
  hide:
  gm:
  executeas:
    aliases: [ea]